### ISSUE TITLE
about the copy-past npm package location

### ISSUE THREAD

**Issue by baoang** [csholmq/vscode-excel-to-markdown-table#1]
Dear csholmq,

I installed this vscode extension, and as instructed, I also installed via npm the copy-past package. However, I found this not working (by *menu bar - view- command palette - Excel to Markdown table*). I guess this might be due to the npm package's location. Should I install the copy-paste package globally, or to some certain dirs? Or should I put `--save` variable?

**Comment by csholmq** [comment]
@baoang The extension depends on the npm package copy-paste. But I don't think you need to install anything outside of VSCode.

I suspect the issue is that the extension has not yet activated. It is only activated when you open a Markdown document.

**Comment by baoang** [comment]
Thank you, @csholmq . You are right!  And thank you again for making such a handy, productive and convenient tool for us.

**Comment by csholmq** [comment]
@baoang Glad you like it! Hope it will help you staying productive.
