### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by ghost** [csholmq/vscode-excel-to-markdown-table#10]
I installed the converter to VS Code. However, when restarted the editor and pressing SHIFT+ALT+v I only see an open menu box and no way to convert the previously copied Excel sheet.

Please provide a clear, step by step description on how this works.

**Comment by csholmq** [comment]
Hi. In the readme it states that you need to either change the document type to Markdown or open/save a Markdown file in order for the extension to activate.
