### ISSUE TITLE
not work on mac

### ISSUE THREAD

**Issue by jeffery9** [csholmq/vscode-excel-to-markdown-table#11]
this extension not works on mac. thanks 

**vscode:**
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Excel:**
office 2019 for mac

**Comment by csholmq** [comment]
What are the symptoms?

**Comment by jeffery9** [comment]
last week, it does not work. but now worked. thanks.
