### ISSUE TITLE
"*" needs to be escaped, for example: "/*" "*/" or simple * 

### ISSUE THREAD

**Issue by aisbergde** [csholmq/vscode-excel-to-markdown-table#19]
I document data models in Excel and export some of them into WIKI entries, the content in Excel contains comments like

```
/*this is a comment
bla*bli*blum
*/
```
the plugin doesn't care about "*" and markdown will interpret parts of the content to italic:
/_this is a comment_
_bla_ bli _blum_
/

"*" should be escaped when converted in markdown

Try this more complex example to check:

```
/*AT:
Sum(IIf([35]="nein",[18]-1,[21]-1)*[9]*[28]*[29]/100) AS Beitrag_BM, 
*/
(IIF(istMitBenchmark = 1, T1.TWR_BM_BW, [T1].[TWR_PF_BW]) - 1)
* T1.VOL_PF_BW

```

**Comment by csholmq** [comment]
That's an interesting use case. It is definitely possible to add escaping to markdown specific characters. But then again that would make it impossible to style your data in Excel before converting it to a table. This sounds more like an unexpected side effect even though I see your issue.

Personally I would find it annoying if this happened automatically and forcing me to post process my markdown table and revert all the escaped characters. Not inclined to add this feature atm. Perhaps as a separate command then.
