### ISSUE TITLE
Handle empty cells

### ISSUE THREAD

**Issue by SimonIMG** [csholmq/vscode-excel-to-markdown-table#2]
Currently, copying an Excel table with empty cells results in just the text being pasted into VS Code.

**Steps to reproduce.**
1. Create an Excel table, but leave some cells throughout it empty
2. Copy the table
3. Use the _Excel to Markdown_ pasting option in VS Code (or just _Shift + Alt + V_)
4. See that there is no table markdown characters, just the contents of the cells.

**Comment by csholmq** [comment]
Hmm, can't seem to reproduce.

![image](https://user-images.githubusercontent.com/1297882/38732574-ea0b430c-3f1e-11e8-85c6-8735a3720fa2.png)

produces

```
| 1 | 2  | 3  | 4  |
|---|----|----|----|
| 5 | 6  |    | 8  |
|   | 10 | 11 | 12 |
```

What platform are you on and which version of Excel?

**Comment by SimonIMG** [comment]
I'm on a Mac and using Excel for Mac v16.12

**Comment by csholmq** [comment]
I don't have Excel on Mac available. Could you paste the raw data as a code snippet to me here?

**Comment by mheden** [comment]
This could be reproduced if the cell is "NULL" i.e. never written. It seems to be working well if the cell content is written and then cleared.

**Comment by DesHorsley** [comment]
@csholmq are you taking pull requests on this project? I'm hitting this issue too, but happy to try work through it.

Windows 10, Excel 365 Pro V1808 Build 10730.20102

**Comment by csholmq** [comment]
@deshorsley Definitely! I have also seen it with the NULL value. Problem is that the data is no longer properly formed as a table so you would have to make assumptions on the format. 
If you do a PR I will be happy to merge. Maybe I'll have a quick look this weekend as well.
