### ISSUE TITLE
It doesn't seem to work with Remote - SSH

### ISSUE THREAD

**Issue by trackds** [csholmq/vscode-excel-to-markdown-table#21]
Other things being equal, it works fine local, but it doesn't work on remote-ssh. It doesn't seem to be getting data from Clipboard

local:
```md
| aa | bb |
|----|----|
| cc | dd |
```

remote:
```md
|  |
|--|
```

**Comment by trackds** [comment]
I think you should use the `VS Code Clipboard API` instead of the `copy-paste module`

**Comment by avilarenan** [comment]
Experiencing the same issue, please consider about this subject!

**Comment by csholmq** [comment]
Thanks for the tip. Will test this on my machine as well.

**Comment by arnoldthebat** [comment]
Same behaviour in WSL2 for reference.

**Comment by csholmq** [comment]
Just released a new version using the new vscode API. Please test and reopen this issue if it still persists.
