### ISSUE TITLE
Does not properly handle cells with newlines in them

### ISSUE THREAD

**Issue by houghtonap** [csholmq/vscode-excel-to-markdown-table#3]
This extension does not properly handle Excel cells that have newlines in them. Here is some CSV that illustrates the issue. The issue presents itself with "Tax Rates" in the Label column.

Label,Content
Tax City Code,002
Tax City Name,Ada
Tax City Type,Village
Tax County Names,Hardin
Tax State Name,Ohio
Member Type,Full
FIPS Code,39-00198
Population,"5,952"
Postal Codes,45810
Income Cutoff,">= $5,000"
Growth Rate,3.0%
"Tax Rates
    2002-2011
    2011-2018","
1.15%
1.65%"
"Penalty Rate
    Minimum
    Maximum","1.5% monthly
$25 once
none"
Interest Rate,1.5% monthly
Tax Lottery,yes
Mandatory Filing,yes

**Comment by csholmq** [comment]
Yeah, the current implementation makes a few assumptions on the data. One is that there are no newlines.

Might fix this down the line.

**Comment by usagi** [comment]
I'm in this ticket. I have the same problem.

**Comment by usagi** [comment]
I got the example raw-data with debugger. It's included the single `\n` datum between `ee` and `ff`.

![image](https://user-images.githubusercontent.com/115972/71904354-4714c900-31a9-11ea-81aa-6c887f78f90f.png)
![image](https://user-images.githubusercontent.com/115972/71904085-cf469e80-31a8-11ea-8ef2-3c8a97db18f7.png)

I think, the issue to be solve easy if we use this unique characteristic maybe. But, I have not OSX(mac) version environment. And in the future, if Excel be got running in an UNIX-like OSs then the easy way will be break.

**Comment by usagi** [comment]
I read the ODF specification and I found this definition: http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part2.html#__RefHeading__1017970_715980110

> 5.14Whitespace
> Whitespace ::= #x20 | #x09 | #x0a | #x0d
> 
> For calculation purposes, whitespace is ignored unless it is inside the contents of string constants or text surrounded by single quotes. Evaluators shall ignore any whitespace characters before and/or after any operators, constant numbers, constant strings, constant errors, inline arrays, parentheses used for controlling precedence, and the closing parenthesis of a function call. Whitespace shall be ignored following the initial equal sign(s). Whitespace shall be ignored just before a function name, but whitespace shall not separate a function name from its initial opening parentheses. Whitespace shall not be used in the interior of a terminating grammar rule (a rule that references no other rule other than character sets, internally or externally-defined), unless specifically permitted by the terminating grammar rule, since these rules define the lexical properties of a component. Evaluators shall not write formulas with whitespace embedded in any unquoted identifier, constant Number, or constant Error.  Evaluators shall treat SPACE (U+0020), CHARACTER TABULATION (U+0009), LINE FEED (U+000A), and CARRIAGE RETURN (U+000D) as whitespace characters.
> 
> An embedded line break shall be represented by a single LINE FEED character (U+000A), not by a carriage return-linefeed pair. When embedded in an XML attribute the linefeed character is represented as “&#x0A;”.
> 
> Evaluators should retain whitespace entered by the original formula creator and use it when saving or presenting the formula, and should not add additional whitespace unless directed to do so during the process of editing a formula.

In other words, even in OSX or an application that call for implementation of ODF, we will be expect only 0x0A 1-byte raw-datum for an intra-cell-newline.

**Comment by usagi** [comment]
Also I read ECMA-376: http://www.ecma-international.org/publications/standards/Ecma-376.htm
I could not found the strict such as ODF definitions. But I found a several examples using intra-cell-newline feature:

ECMA-376 5th edition Part 1 §18. SpreadsheetML Reference Material page-1647: `[Example: `

![image](https://user-images.githubusercontent.com/115972/71910950-33239400-31b6-11ea-917a-60ffdd2fdfd0.png)

And I made a simple `.xlsx` file and extract using zip then I got the result in `xl/sharedStrings.xml`:

![image](https://user-images.githubusercontent.com/115972/71911316-d7a5d600-31b6-11ea-98a3-714272eb7673.png)

Oops, we cannot use the file-level specs.

**Comment by usagi** [comment]
However, I got the GOOD news from my twitter friend: https://twitter.com/Pyon_Pyon_/status/1214576247918870530

mac 10.15.2, Excel 16.28:

```sh
$ pbpaste | hexdump -C
00000000  61 61 61 09 62 62 62 09  63 63 63 0d 0a 64 64 64  |aaa.bbb.ccc..ddd|
00000010  09 22 65 65 0a 66 66 22  09 67 67                 |."ee.ff".gg|
0000001b
```

My first idea as easy way can be solve the issue in Windows, and also the way is safe in OSX(mac) too. Thus, conclusion is:

- Add the replacing from `/[^\r]\n/` to `<br/>` into the line before `helper.splitIntoRowsAndColumns`.

I'll create PR soon. 🙆‍♀️

**Comment by usagi** [comment]
(WiP)

![image](https://user-images.githubusercontent.com/115972/71915207-9b767380-31be-11ea-8f55-b687d47fb847.png)
↑from:Excel / to:md↓
![image](https://user-images.githubusercontent.com/115972/71915226-a3ceae80-31be-11ea-9c7f-6358ebc17107.png)

I need more time to solve the additional `"` char problem. Wait a time plz.

**Comment by usagi** [comment]
(WiP)

![image](https://user-images.githubusercontent.com/115972/71942410-76a2f000-3200-11ea-93cd-55a5777c6850.png)
↑from:Excel / to:powershell`Get-Clipboard | Format-Hex`
![image](https://user-images.githubusercontent.com/115972/71942441-989c7280-3200-11ea-9e84-571ed9019db1.png)

`"` rules of Excel is:

1. Escape the cell using `"` if included `\n` in the cell
    - e.g. cell-x-in-Excel=`ee\nff` --> copy to clipboard --> clipboard.raw-data=`"ee\nff"`
2. Escape the `"` to `""` if included `"` in the cell match to rule-1
    - e.g. cell-x-in-Excel=`"dd\nzz"` --> copy to clipboard --> clipboard.raw-data=`"""ee\nff"""`
        - (explaining): `{ "(rule-1), "(rule-2[0]), "(rule-2[1]), d, d, \n, z, z, "(rule-2[0]), "(rule-2[0]), "(rule-1) }`

---

And, also I got a BAD news in WSL.

![image](https://user-images.githubusercontent.com/115972/71943051-a3f09d80-3202-11ea-96a9-9737254a9f9a.png)

`\r` be gone. lol Thus, we cannot use the technique in the case:

1. Make or open a table using Excel on Windows
2. Copy a table
3. Paste into WSL environments

I guess, cause of this behavior is X Window server on Windows platform maybe.(X410, etc.). But, I think we can ignoring the case. Because VSCode has WSL special mode and then most users are not use native-VSCode with this extension feature on a WSL environment. ( See also https://code.visualstudio.com/remote-tutorials/wsl/run-in-wsl )

**Comment by usagi** [comment]
GOOD news, I completed the implementation.

![image](https://user-images.githubusercontent.com/115972/71946251-9b04c980-320c-11ea-99bd-852317aff57c.png)
↑ from: Excel / to: VSCode with this feature ↓
![image](https://user-images.githubusercontent.com/115972/71946268-a657f500-320c-11ea-918d-803e1b58bc85.png)
↓ and preview; expected!
![image](https://user-images.githubusercontent.com/115972/71946494-62b1bb00-320d-11ea-932a-36fa9103c85a.png)

It was required to be a few complicated regex usage. Anyway, it's completed. I'll PR soon. 😆

**Comment by usagi** [comment]
PR https://github.com/csholmq/vscode-excel-to-markdown-table/pull/15
