### ISSUE TITLE
On a Mac, only shift+option+v works, not paste

### ISSUE THREAD

**Issue by Blindfreddy** [csholmq/vscode-excel-to-markdown-table#30]
Tried this on my Mac and thought I was going insane: selecting `paste` from the context menu only insert normal text. Then I tried the keyboard combination `shift+option+v`and it works !

**Comment by csholmq** [comment]
Could you record a GIF for me?

**Comment by wchisenski** [comment]
Hi @Blindfreddy,

I think that's the _expected_ behavior of the extension. If you look in the command palette, it specifically calls out using <kbd>⇧ Shift</kbd> + <kbd>⌥ Option</kbd> + <kbd>V</kbd>. The standard paste will simply give you plain text.

![image](https://user-images.githubusercontent.com/53623427/222261250-b33cf2db-90b5-467d-ba07-c383e7bcbc23.png)

Hope this clears up the issue. @csholmq, you should be able to close this.

**Comment by csholmq** [comment]
Thanks @wchisenski
