### ISSUE TITLE
Does not support chinsese

### ISSUE THREAD

**Issue by yufangcheng** [csholmq/vscode-excel-to-markdown-table#7]
Plaform: macOs Mojave v10.14.1
Excel: v16.20(181208)

**Comment by csholmq** [comment]
Could you supply me with some example data?

**Comment by jizhou-wu** [comment]
One small example data could be like this: https://1drv.ms/x/s!AsnuK1YsM3jYkAPJuvOFoGoqBAcV?e=8nXEvN

I also find there is a related issue in copy-excel-paste-markdown repository: [GBK character show replaced with "???" when it pasted](https://github.com/jonmagic/copy-excel-paste-markdown/issues/6)

**Comment by csholmq** [comment]
@wuchichou It appears to be working for me on Win10.

![bild](https://user-images.githubusercontent.com/1297882/72676646-eda77680-3a93-11ea-8a7b-e4ff2d7e5ff9.png)

Is this only an issue on MacOS?

**Comment by jizhou-wu** [comment]
@csholmq Yes, the problem also happens here in macOS Mojave version 10.14.6.

**Comment by libukai** [comment]
@csholmq yes,I have the same problem.

**Comment by rxg9527** [comment]
@csholmq i also have this problem in my mac.

But use the copy-excel-paste-markdown repository @wuchichou mentioned, i didn't encounter that issue [GBK character show replaced with "???" when it pasted](https://github.com/jonmagic/copy-excel-paste-markdown/issues/6)  .It runs well.

I hope this helps.

If you need some Chinese character, see below.

| 姓名 | 年龄 |
|----|----|
| 张三 | 20 |
| 李四 | 18 |

**Comment by johnking** [comment]
I found the same issue with MacOS

**Comment by csholmq** [comment]
Just released a new version using the new vscode API. Please test and reopen this issue if it still persists.
