### ISSUE TITLE
command 'extension.excelToMarkdown' not found

### ISSUE THREAD

**Issue by pistolilla** [csholmq/vscode-excel-to-markdown-table#8]
Hi, just after I upgraded to 1.30 I got this message:
```
command 'extension.excelToMarkdown' not found
```
I've tried uninstalling, reloading and installing again but unsuccessfully.

**Comment by csholmq** [comment]
Hi. Have you opened a Markdown file?

**Comment by dougxwok2** [comment]
This is a bug.

If you try to use the command in a text file, it displays an error: 

> command 'extension.excelToMarkdown' not found

To anyone else who finds this bug, the work around is:

- Create a new file
- Save it as `file.md` so it is a markdown file

The extension will not run with no error when you use it in that file.

**Comment by csholmq** [comment]
@dougxwok2 This is actually by design. From the readme:

> Extension is only first activated when editing a Markdown document. You will need to change the language setting in VS Code to use 'markdown' to enable this extension.

**Comment by dougxwok2** [comment]
@csholmq It is a bug. It shouldn't show a generic 'command not found' error message when you attempt to use the command from the command palette in a regular file.

**Comment by csholmq** [comment]
@dougxwok2 Point taken. Probably is a way of addressing that.

**Comment by csholmq** [comment]
@dougxwok2 Just pushed a fix. Let me know if it works for you.
